### ISSUE TITLE
A request for complete code

### ISSUE THREAD

**Issue by Hengwei-Zhao96** [Dzeiberg/ClassPriorEstimation#1]
Thank you for your outstanding work at class prior estimation, I read your AAAI 2020 paper "Fast Nonparametric Estimation of Class Proportions in the Positive-Unlabeled Classification Setting", I want to follow your work at class prior estimation but the link cann't be open beacuse I haven't Khoury username and password, and the code in your github may not complete,so,could you please share me a complete code for Fast Nonparametric Estimation of Class Proportions at your convenience, my e-mail is whu_zhaohw@whu.edu.cn,thank you!

**Comment by Dzeiberg** [comment]
Glad you're interested. This repository has the same contents as the one I accidentally linked to in the paper. What you see here contains everything you should need to follow our work. Let me know if you have any issues with this.
